#!/usr/bin/env bash
# find-data-flows.sh - Phase 3 accelerator. Greps the codebase for known
# third-party SDK / API patterns to seed the code-audit agent's work.
# Output is a markdown starter that the agent refines with file:line evidence.
#
# Usage: ./find-data-flows.sh [repo_root]
#
# Run from the repo root, or pass the path.

set -u

REPO="${1:-.}"
cd "$REPO" || exit 1

echo "# Data-flow starter inventory"
echo
echo "_Generated by find-data-flows.sh. Each hit is a signal that the named SDK / API / domain is in the codebase and must be considered for the sub-processor list. The Phase 3 code-audit agent must replace each entry with file:line citations and retention behaviour._"
echo
echo "_Run date: $(date +%Y-%m-%d)_"
echo

scan() {
  local label="$1"
  local pattern="$2"
  local count
  count=$(grep -rE "$pattern" \
    --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
    --include="*.py" --include="*.rb" --include="*.go" --include="*.php" \
    --include="*.env.example" --include="*.json" \
    --exclude-dir="node_modules" --exclude-dir=".next" --exclude-dir="dist" \
    --exclude-dir=".git" --exclude-dir="build" --exclude-dir=".claude" \
    . 2>/dev/null | wc -l)
  if [ "$count" -gt 0 ]; then
    echo "- **$label** ($count hits)"
  fi
}

echo "## Auth / Identity"
scan "Supabase Auth" "supabase.*auth|@supabase/auth|createServerClient|createClient.*supabase"
scan "Clerk" "@clerk/|clerk.dev|CLERK_SECRET"
scan "Auth0" "@auth0/|auth0.com|AUTH0_DOMAIN"
scan "NextAuth" "next-auth|NextAuth\("
scan "Firebase Auth" "firebase/auth|FIREBASE_API_KEY"
scan "Google OAuth" "accounts.google.com|GOOGLE_CLIENT_ID|googleusercontent"
echo

echo "## Database / Storage"
scan "Supabase DB/Storage" "supabase.*from\(|supabase.*storage|from('[a-z_]+')"
scan "Postgres direct" "pg.Client|Pool\(|PG_CONNECTION_STRING"
scan "MongoDB" "mongodb\+srv|mongoose|MongoClient"
scan "Firebase Firestore" "firestore|@firebase/firestore"
scan "Neon" "neon.tech|@neondatabase"
scan "PlanetScale" "planetscale|@planetscale"
scan "Upstash Redis" "upstash|@upstash/redis"
scan "Redis direct" "createClient.*redis|REDIS_URL"
scan "S3 / R2 / GCS" "aws-sdk|@aws-sdk|s3Client|cloudflare.*r2|@google-cloud/storage"
echo

echo "## AI providers"
scan "OpenAI" "openai|api.openai.com|OPENAI_API_KEY"
scan "Anthropic" "@anthropic-ai|api.anthropic.com|ANTHROPIC_API_KEY"
scan "Vercel AI SDK" "@ai-sdk|vercel/ai|ai/react"
scan "Cohere" "cohere-ai|cohere.com"
scan "Hugging Face" "huggingface|@huggingface"
scan "Replicate" "replicate.com|replicate-javascript"
scan "ElevenLabs" "elevenlabs|elevenlabs.io"
scan "Gemini / Google AI" "generativeai|ai.google.dev"
echo

echo "## Payments"
scan "Stripe" "stripe.com|@stripe/|STRIPE_SECRET"
scan "Paddle" "paddle.com|@paddle"
scan "Polar" "polar.sh|@polar-sh"
scan "Lemon Squeezy" "lemonsqueezy|LEMON_SQUEEZY"
echo

echo "## Email / Messaging"
scan "Resend" "resend.com|@resend/|RESEND_API_KEY"
scan "Postmark" "postmark.com|@postmark"
scan "SendGrid" "sendgrid|@sendgrid"
scan "Mailgun" "mailgun|MAILGUN_API_KEY"
scan "AWS SES" "ses-client|SendEmailCommand"
scan "Twilio / SMS" "twilio.com|@twilio"
scan "WhatsApp - WaSender" "wasenderapi|wasender"
scan "WhatsApp - direct Meta" "graph.facebook.com.*whatsapp|WHATSAPP_TOKEN"
scan "Telegram" "api.telegram.org|telegraf|@telegraf"
scan "Slack" "slack.com/api|@slack/"
scan "Discord" "discord.com/api|discord.js"
echo

echo "## Analytics / Observability"
scan "PostHog" "posthog.com|posthog-js|POSTHOG_API_KEY"
scan "Mixpanel" "mixpanel.com|mixpanel-browser"
scan "Amplitude" "amplitude.com|@amplitude"
scan "Google Analytics" "googletagmanager|google-analytics|gtag\("
scan "Plausible" "plausible.io|plausible.com"
scan "Fathom" "fathom.com|usefathom"
scan "Segment" "segment.com|@segment/|analytics.js"
scan "Sentry" "sentry.io|@sentry/|SENTRY_DSN"
scan "LogRocket" "logrocket.com|logrocket"
scan "Datadog" "datadoghq|datadog-logs"
scan "Vercel Analytics" "@vercel/analytics|vercel-analytics"
scan "Fullstory / Hotjar / session replay" "fullstory.com|hotjar.com|session-replay"
echo

echo "## Scrapers / APIs"
scan "Apify" "apify.com|apify-client|APIFY_TOKEN"
scan "Jina Reader" "r.jina.ai|jina.ai"
scan "weserv.nl image proxy" "images.weserv.nl|weserv.nl"
scan "ScrapingBee / Bright Data" "scrapingbee|brightdata|luminati"
scan "Exa / Perplexity API" "api.exa.ai|perplexity.ai"
echo

echo "## CDN / Hosting"
scan "Vercel" "VERCEL|vercel.app|@vercel/"
scan "Cloudflare" "cloudflare.com|CF_API_TOKEN|cf-workers"
scan "Netlify" "netlify.com|NETLIFY_"
scan "Fly.io" "fly.io|fly.toml"
scan "Render" "render.com|RENDER_"
echo

echo "## Cookies / storage keys"
scan "document.cookie" "document\.cookie"
scan "localStorage writes" "localStorage\.setItem|localStorage\["
scan "sessionStorage writes" "sessionStorage\.setItem|sessionStorage\["
echo

echo "## Security-adjacent"
scan "CSP header" "Content-Security-Policy"
scan "HSTS" "Strict-Transport-Security"
scan "RLS enablement" "ENABLE ROW LEVEL SECURITY|enable row level security"
scan "Rate limit libs" "@upstash/ratelimit|express-rate-limit|iron-session"
echo

echo "## Raw fetch destinations (suspicious - audit each)"
echo
echo "_Unique hostnames appearing in source code._"
echo
grep -rhE "https://[a-zA-Z0-9.-]+" \
  --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
  --include="*.py" --include="*.rb" --include="*.go" \
  --exclude-dir=node_modules --exclude-dir=.next --exclude-dir=dist \
  --exclude-dir=.git --exclude-dir=build --exclude-dir=.claude \
  . 2>/dev/null | \
  grep -oE "https://[a-zA-Z0-9.-]+" | \
  sort -u | \
  grep -vE "(schema\.org|w3\.org|github\.com|npmjs\.com|example\.com|localhost|tailwindcss\.com|mozilla\.org|fonts\.googleapis)" | \
  head -30 | \
  sed 's/^/- /'
echo

echo "---"
echo
echo "_Next step: pass this file to the Phase 3 code-audit agent as 'starter inventory'. It will replace each entry with file:line evidence and produce the final \`specs/legal/data-practices-audit-*.md\`._"
